# yaml for checking tags
# check ONLY the file being updated ends in .md

name: linting-blogs-tags

on:
  pull_request:
    paths:
      - '**.md'
  push:
    paths:
      - '**.md'

# the tags should be like: tags: A, B, C, strip into A B C
jobs:
  check-tags:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install markdown
      - name: Check for tags
        run: |
          FILES=$(git diff --name-only ${{ github.event.after }} ${{ github.event.before }})

          for FILE in $FILES; do
            if [[ $FILE == *.md ]]; then
              echo "Checking tags in $FILE"
              ERROR=$(python3 check-tags.py <<< $FILE)
              if [ '$ERROR' == 1 ]; then
                echo "Error in $FILE: $ERROR"
                exit 1
              fi
            fi
          done

          FILES=$(git ls-files | grep .md | sed 's/[^a-zA-Z0-9\/\._-]/ /g')
          echo $FILES

          for FILE in $FILES; do
            if [[ $FILE == *.md ]]; then
              echo "Checking tags in $FILE"
              ERROR=$(python3 check-tags.py <<< $FILE)
              if [ '$ERROR' == 1 ]; then
                echo "Error in $FILE: $ERROR"
                exit 1
              fi
            fi
          done
